@echo off
echo Setting up backend environment...
if not exist venv (
    echo Creating virtual environment...
    python -m venv venv
)
call venv\Scripts\activate.bat
echo Installing requirements...
pip install -r requirements.txt
echo Starting FastAPI server...
uvicorn main:app --host 0.0.0.0 --port 8000 --reload
